### ISSUE TITLE
Crash on Next.js Edge runtime

### ISSUE THREAD

**Issue by johanneskares** [svapnil/iso20022.js#16]
Thanks for your work. 

The library is not supported in Next.js edge runime.

**Comment by svapnil** [comment]
Hey @johanneskares ,

Will look into reproducing the issue as soon as I can! Will see if I can solve it

**Comment by svapnil** [comment]
@johanneskares 

I'm wondering if you found a reasonable solution for your Next.js work - I'm also able to reproduce some weirdness going on when running iso20022.js on an Edge / api route. 

Going to figure out what a reasonable fix is

**Comment by svapnil** [comment]
I looked into this issue and it seems like with the latest version of iso20022.js we are able to run this on next.js backends. 

The Next.js Edge runtime hasn't been tested, but since this is a middleware specific route it is unlikely to run iso20022.js code.
